name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOC_PATH: target/doc

jobs:
  test:
    name: ${{ matrix.readable_os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          readable_os: Ubuntu
        - os: windows-latest
          readable_os: Windows
        - os: macos-latest
          readable_os: macOS
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - uses: actions-rs/cargo@v1
      with:
        command: test
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: doc
    - name: Copy Doc Index Page
      run: cp .github/pages/index.html ${{ env.DOC_PATH }}
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: llvm-tools-preview
    - name: Install grcov
      run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar -xj && mv grcov ~/.cargo/bin/
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        RUSTFLAGS: -Z instrument-coverage
        RUSTDOCFLAGS: -Z instrument-coverage -Z unstable-options --persist-doctests target/debug/doctestbins
        LLVM_PROFILE_FILE: coverage-%p-%m.profraw
    - name: Run grcov
      run: grcov . --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov
    - name: Coveralls Upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
